extends SceneTree
const Combo = preload("res://scripts/combo_meter.gd")
func _initialize() -> void:
	var combo := Combo.new()
	assert(combo.rank_index() == -1)
	combo.register_hit()
	assert(combo.rank_index() == 0)
	combo.advance(3.0)
	assert(combo.rank_index() == 0)
	combo.register_hit()
	assert(is_equal_approx(combo.remaining, 4.0))
	combo.reset()
	combo.register_kill()
	assert(combo.rank_index() == 0)
	for i in range(8):
		combo.register_kill()
	assert(combo.rank_index() == 8)
	combo.register_kill()
	assert(combo.points == 27)
	combo.advance(4.0)
	assert(combo.rank_index() == 7)
	combo.advance(4.0)
	assert(combo.rank_index() == 6)
	combo.advance(28.0)
	assert(combo.rank_index() == -1)
	assert(combo.remaining == 0.0)
	combo.register_hit()
	combo.reset()
	assert(combo.points == 0)
	combo.free()
	print("PASS: hit, kill, refresh, SSS cap, gradual decay, expiry, reset")
	quit()
