extends SceneTree
const Combo = preload("res://scripts/combo_meter.gd")
func _initialize() -> void:
	var combo = Combo.new()
	assert(combo.rank_index() == -1)
	combo.register_hit()
	assert(combo.rank_index() == 0)
	combo.advance(2.9)
	assert(combo.points == 1)
	combo.advance(0.2)
	assert(combo.points == 0)
	combo.add_points(20)
	assert(combo.rank_index() == 0)
	combo.register_hit()
	assert(combo.rank_index() == 1)
	combo.reset()
	for i in 8:
		combo.register_kill()
	assert(combo.points == 24 and combo.rank_index() == 1)
	combo.add_points(10000)
	assert(combo.points == 10024 and combo.rank_index() == 8)
	combo.advance(3.0)
	assert(combo.points == 10004 and combo.rank_index() == 8)
	combo.advance(6.0)
	assert(combo.points == 9964)
	combo.reset()
	assert(combo.points == 0 and combo.rank_index() == -1)
	combo.free()
	print("PASS harder combo ranks, unlimited points beyond SSS, gradual decay and reset")
	quit()
