extends SceneTree
const Run = preload("res://scripts/run_state.gd")
func _initialize() -> void:
	var run = Run.new()
	run.rng.seed = 12345
	assert(run.catalog.items.size() == 20)
	assert(run.catalog.by_id.size() == 20)
	assert(run.catalog.weapon_name("Knight") == "Sword")
	assert(run.catalog.weapon_name("Ninja") == "Katana")
	assert(run.catalog.weapon_name("Daddy") == "Not assigned")
	assert(run.level == 1 and run.offers.is_empty())
	run.add_xp(9)
	assert(run.level == 1 and run.xp == 9)
	run.add_xp(1)
	assert(run.level == 2 and run.offers.size() == 3)
	assert(not run.choose_item("not_an_item"))
	run.free()
	run = Run.new()
	for i in range(10):
		run.offers.assign(["pencil", "red_dot", "sandal"])
		assert(run.choose_item("pencil"))
	assert(run.owned_ids.size() == 1)
	assert(run.total_items() == 10 and run.stack_count("pencil") == 10)
	assert(run.stats()["attack"] == 110)
	assert(not run.choose_item("pencil"))
	var repeat_seen := false
	for i in range(250):
		var choices: Array = run.roll_choices(2 + i)
		assert(choices.size() == 3)
		assert(choices[0] != choices[1] and choices[1] != choices[2] and choices[0] != choices[2])
		repeat_seen = repeat_seen or choices.has("pencil")
	assert(repeat_seen)
	run.add_xp(45)
	assert(run.level == 4 and run.reward_level == 2 and run.pending_levels.size() == 2)
	var stale_generation: int = run.offer_generation
	run.offers.assign(["pencil"])
	assert(run.choose_item("pencil", stale_generation))
	run.offers.assign(["pencil"])
	assert(not run.choose_item("pencil", stale_generation))
	assert(run.choose_item("pencil", run.offer_generation))
	assert(run.reward_level == 4)
	assert(run.choose_item(run.offers[0]))
	assert(run.offers.is_empty() and run.pending_levels.is_empty())
	run.free()
	run = Run.new()
	for item in run.catalog.items:
		run.offers.assign([item["id"]])
		assert(run.choose_item(item["id"]))
	assert(run.owned_ids.size() == 20 and run.total_items() == 20)
	assert(run.stats()["max_hp"] == 620 and run.stats()["attack"] == 300)
	assert(run.stats()["speed"] == 125 and run.stats()["luck"] == 8.5)
	assert(run.stats()["crit_chance"] == 23.5 and run.stats()["crit_damage"] == 187)
	run.test_level_up()
	assert(run.offers.size() == 3)
	var repeated: String = run.offers[0]
	assert(run.choose_item(repeated))
	assert(run.stack_count(repeated) == 2 and run.total_items() == 21)
	assert(run.rarity_weights(2)["common"] > run.rarity_weights(20)["common"])
	assert(run.rarity_weights(2)["legendary"] < run.rarity_weights(20)["legendary"])
	run.free()
	print("PASS: repeated rewards, Pencil x10 = +100 ATK, stack totals, unique cards, stale pick rejection, XP queue, all-types continuation")
	quit()
